name: Payment Gateway

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK (Release)
        run: flutter build apk --release --build-name=1.0.0 --build-number=1

      # Optional: Upload APK to GitHub as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: payment_gateway-apk
          path: build/app/outputs/flutter-apk/app-release.apk
